### PR TITLE
Fixing multiprocessing python tests on Linux

### PR DESCRIPTION
**Pull request by madhavajay**
- Changed set_start_method to "spawn" and added daemon=True

## Description
This PR fixes the linux test hanging issue:
https://github.com/OpenMined/syft_experimental/issues/3

## Affected Dependencies
None

## How has this been tested?
Github Actions

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@replomancer Thanks for figuring out the linux spawn issue: https://github.com/OpenMined/syft_experimental/issues/3
I have added "spawn" and daemon=True and now the tests generally pass, however there appears to be another weird gremlin.

The first test on Linux always fails to connect, see some of the past failed ones:
https://github.com/OpenMined/syft_experimental/actions?query=workflow%3APython

I tried all sorts of timeouts, different ports, interfaces etc, none mattered. So for now by running a failing test which has no asserts first, everything just works, which is weird.

I wonder if you are able to replicate this on your machine. I suspect that its running inside a container so perhaps we need to do that to be able to simulate the linux CI environment failing? Since docker on macOS is just linux in a VM, my guess is that the mac CI doesnt use docker.

In the worst case I can live with the fake first warmup test, but it would be nicer if we understood why this fails and could fix it.

Edit: It seems to be flapping on MacOS as well.
https://github.com/OpenMined/syft_experimental/runs/942955200?check_suite_focus=true

**Comment by madhavajay** [comment]
This test has passed twice in a row now, but I am still suspicious:
https://github.com/OpenMined/syft_experimental/actions

**Comment by replomancer** [comment]
When I run pytest now I see this window :sparkles:

python_stopped

but not always :see_no_evil: 

> The first test on Linux always fails to connect

Same for me if I comment out  `test_warmup`.

I'm looking into it.

**Comment by replomancer** [comment]
LGTM

One suggestion: we can replace this
```python
mp.set_start_method("spawn", force=True)
```
with this:
```python
def setup_module():
    mp.set_start_method("spawn", force=True)
```
[pytest documentation](https://docs.pytest.org/en/latest/xunit_setup.html?highlight=setup_module#module-level-setup-teardown)

**Review by replomancer — CHANGES_REQUESTED** [review]
LGTM

One suggestion: we can replace this
```python
mp.set_start_method("spawn", force=True)
```
with this:
```python
def setup_module() -> None:
    mp.set_start_method("spawn", force=True)
```
[pytest documentation](https://docs.pytest.org/en/latest/xunit_setup.html?highlight=setup_module#module-level-setup-teardown)

**Comment by madhavajay** [comment]
> LGTM
> 
> One suggestion: we can replace this
> 
> ```python
> mp.set_start_method("spawn", force=True)
> ```
> 
> with this:
> 
> ```python
> def setup_module() -> None:
>     mp.set_start_method("spawn", force=True)
> ```
> 
> [pytest documentation](https://docs.pytest.org/en/latest/xunit_setup.html?highlight=setup_module#module-level-setup-teardown)

Great suggestion, I have added it.

**Pull request merged**
